# Generated by Django 5.0.6 on 2024-06-14 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('releasedate', models.DateField()),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('horror', 'Horror'), ('drama', 'Drama')], max_length=100)),
                ('length', models.PositiveIntegerField()),
                ('image_banner', models.ImageField(upload_to='movi_images/')),
                ('image_cover', models.ImageField(upload_to='movi_images/')),
                ('video', models.FileField(upload_to='movie_videos/')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
