# Generated by Django 5.0.6 on 2024-06-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_movie_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.FloatField(default=0),
        ),
    ]
