# Generated by Django 5.0.6 on 2024-06-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_movie_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_list',
            name='m_id',
            field=models.TextField(default=0),
        ),
    ]
