# Generated by Django 5.0.6 on 2024-06-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='coming_soon',
            field=models.TextField(default=1),
        ),
    ]
