# Generated by Django 5.0.6 on 2024-06-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_movie_coming_soon'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.TextField(default='null'),
        ),
    ]
